// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void SimpleGoogleTest() {
    driver.Navigate().GoToUrl("https://www.google.com/");
    driver.FindElement(By.Id("APjFqb")).SendKeys("kyndryl");
    driver.FindElement(By.CssSelector(".LLD4me")).Click();
    driver.FindElement(By.CssSelector("center:nth-child(1) > .gNO89b")).Click();
    driver.FindElement(By.CssSelector(".g > .kvH3mc .LC20lb")).Click();
    driver.FindElement(By.CssSelector(".cmp-homepage-hero__title")).Click();
    Assert.Equal(driver.FindElement(By.CssSelector(".cmp-homepage-hero__title")).Text, "O coração do progresso™");
    driver.Close();
  }
}
